name: main ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Zig
        uses: mlugg/setup-zig@v1
      - name: Check format
        continue-on-error: true
        run: zig fmt --check .
      - name: Build debug
        run: zig build -Doptimize=Debug -p zig-out/debug
      - name: Build release
        run: zig build -Doptimize=ReleaseFast -p zig-out/release
      - name: Run tests
        run: zig build test

